"""Add is_private to Room

Revision ID: 76243c0ff457
Revises: 197618a7f1a2
Create Date: 2025-04-16 13:11:27.864638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76243c0ff457'
down_revision = '197618a7f1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rules', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('rules')
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###
