"""Update models

Revision ID: cd64a5428609
Revises: 7bac3e47c6cb
Create Date: 2026-01-06 23:02:36.082137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd64a5428609'
down_revision = '7bac3e47c6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drawing_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_chat_message_drawing_id', 'drawing', ['drawing_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_message_drawing_id', type_='foreignkey')
        batch_op.drop_column('drawing_id')

    # ### end Alembic commands ###
